# Generated by Django 2.0.1 on 2020-06-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transactions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
