# Generated by Django 2.0.1 on 2020-06-24 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200616_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 19, 32, 9, 213105)),
        ),
    ]
