# Generated by Django 2.1.1 on 2020-10-05 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200624_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
