# Generated by Django 2.1.5 on 2020-10-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201005_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='route',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
