# Generated by Django 2.1.5 on 2020-10-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201008_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ssn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
