# Generated by Django 2.1.5 on 2020-10-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
