# Generated by Django 2.1.5 on 2020-11-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201014_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='recipient_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
