# Generated by Django 2.1.5 on 2020-11-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201122_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='otp',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
