# Generated by Django 2.1.5 on 2020-12-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_transactions_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
