# Generated by Django 2.1.5 on 2021-01-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_disable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_id',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
