# Generated by Django 2.1.5 on 2021-01-10 18:43

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_id',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=app.models.account_upload),
        ),
    ]
